# Generated by Django 5.0.7 on 2024-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tgnic',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
